name: Build Pre-processed Data

on:
  push:
    branches:
      - main
    paths:
      - 'data/used/**.csv'
      - 'data/legend/**.csv'
  workflow_dispatch:

jobs:
  build-data-file:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run Zsh build script and save output
        run: |
          chmod +x build_price_data.zsh
          ./build_price_data.zsh > data/prebuilt_prices.json

      - name: Commit and push pre-built data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'CI: Auto-build pre-processed price data'
          file_pattern: data/prebuilt_prices.json
          commit_user_name: 'GitHub Actions Bot'
          commit_user_email: 'github-actions[bot]@users.noreply.github.com'
