name: Sync External Folder

on:
  schedule:
    - cron: '0 6 * * *'  # Runs every day at 6:00 AM UTC
  workflow_dispatch:       # Allow manual trigger

jobs:
  sync-folder:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout your repo
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Clone source repo
      run: |
        git clone --depth 1 https://github.com/ddm999/gt7info.git data

    - name: Copy folder to your repo
      run: |
        rm -rf data
        cp -r data data

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git diff --quiet && git diff --staged --quiet || git commit -m "Update external folder from source repo"
        git push
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
